# Generated by Django 4.2.2 on 2023-08-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto_tochka', '0002_alter_service_options_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Бренд машины')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Бренд машины',
                'verbose_name_plural': 'Бренды машин',
            },
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(max_length=2500, verbose_name='Текст комментария'),
        ),
    ]
