# Generated by Django 4.2.2 on 2023-08-08 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avto_tochka', '0003_brand_alter_comments_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Запчасти')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.SmallIntegerField(default=0, verbose_name='Цена')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('photo', models.ImageField(upload_to='photos/products/%Y/%m/%d/', verbose_name='Фото')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avto_tochka.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Наименование',
                'verbose_name_plural': 'Наименование',
                'ordering': ['id'],
            },
        ),
    ]
