# Generated by Django 4.2.2 on 2023-08-09 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avto_tochka', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Запчасть', 'verbose_name_plural': 'Запчасти'},
        ),
    ]
