# Generated by Django 4.2.2 on 2023-08-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto_tochka', '0006_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=True, verbose_name='Новая запчасть'),
        ),
    ]
