# Generated by Django 4.2.2 on 2023-08-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto_tochka', '0008_alter_product_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=255, verbose_name='Модель'),
        ),
    ]
