# Generated by Django 4.2.2 on 2023-08-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto_tochka', '0009_alter_product_content_alter_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.SmallIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
